midas:
  kafka:
    topic: transactions

general:
  kafka-topic: trader-updates

server:
  port: 33400

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: midas-group

incentive:
  url: http://localhost:8080/incentive
